codebook/codebook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .routers import router

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('posts.urls', namespace='posts')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^restapi/', include(router.urls, namespace='restapi')),
    url(r'^admin/', admin.site.urls),
]

codebook/home/urls.py
from django.conf.urls import url

from .views import sign_up, home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^signup/$', sign_up, name='signup'),
]

codebook/posts/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
    url(r'^question/(?P<pk>[0-9]+)/$', views.QuestionView.as_view(), name='question-detail'),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.TagView.as_view(), name='tag-detail'),
    url(r'^questions/$', views.QuestionsList.as_view(), name='questions-list'),
    url(r'^questions/popular/$', views.PopularQuestionsList.as_view(), name='popular-questions'),
    url(r'^questions/latest/$', views.LatestQuestionsList.as_view(), name='latest-questions'),
    url(r'^tags/$', views.TagsList.as_view(), name='tags-list'),
    url(r'^tags/trending/$', views.TrendingTagsList.as_view(), name='trending-tags'),
]

codebook/profiles/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
    url(r'^$', views.GoToProfile.as_view(), name='go-to-profile'),
    url(r'^(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile-detail'),
]

codebook/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Codebook{% endblock title %}</title>
    <style> {% block style %}{% endblock style %} </style>
    <link rel="stylesheet" href="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="  crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script language="javascript" type='text/javascript' src="{% static 'js/knockout-3.4.2.js' %}"></script>
    <script language="javascript" type='text/javascript' src="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <script language="javascript" type='text/javascript' src="{% static 'js/knockout-jqAutocomplete.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'js/constants.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'js/base.js' %}"></script>
</head>
<body>

  <header id="header">
    <h1><a href="{% url 'home' %}"> Look for answers in Codebook </a></h1>

    <nav id="nav">
	<ul>
 	{% if user.is_authenticated %}
          <li><a href="{% url 'posts:latest-questions' %}">Latest Questions</a></li>
          <li><a href="{% url 'posts:trending-tags' %}">Trending Tags</a></li>
          <li><a href="{% url 'profiles:go-to-profile' %}">My Profile</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'signup' %}">Sign up</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
	</ul>
    </nav>
  </header>

    <div id="main">
        {% include 'messages_display.html' %}
        <div class="container" id="container">
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

codebook/templates/messages_display.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}